image: rainu/docker-node

stages:
  - test
  - build
  - dockerrize

variables:
  CFG_MONGO_HOST: "mongo"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

test:
  stage: test
  services:
    - name: mongo
      alias: mongo
  script:
    - npm install
    - npm run test

build-server:
  stage: build
  script:
    - npm install
    - npm run build

build-course-crawler:
  stage: build
  script:
    - npm install
    - npm run build-course
  artifacts:
    paths:
    - ./services/course-crawler/dist
    expire_in: 5 minutes

dockerrize:
  image: tmaier/docker-compose:latest
  stage: dockerrize
  script:
    - echo "{\"build\":{\"version\":\"${CI_COMMIT_SHA}\", \"date\":$(date +'%s' )000}}" > ./common/project-info.json
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker-compose build
    - docker-compose push
  dependencies:
    - build-server
    - build-course-crawler
  only:
    - master
