version: '2'

services:

  course:
    image: rainu/cryptotrack-course-ng
    build:
      context: ./services/course-crawler/
    environment:
      - CFG_MONGO_HOST=db
    depends_on:
      - db

  db:
    image: mongo
    restart: always
